print:
	echo "first print from make file"

# here both the command and the output of the command are printed
# comments are not printed

#  the below commented lines give ehat i have done
# l13@pl13:~/Documents/git/makefile_tutorial/module_1$ make
# echo "first print from make file"
# first print from make file

print_no_command:
	@echo "print without command getting printed" 


# l13@pl13:~/Documents/git/makefile_tutorial/module_1$ make
# echo "first print from make file"
# first print from make file

