all:
	echo $$env_variable
	echo $(env_variable)

#  output

# pl13@pl13:~/Documents/git/makefile_tutorial/module_13$ export env_variable=amruth ; make
# echo $env_variable
# amruth
# echo amruth
# amruth