test1: test1.o

test1.c:
	echo "int main() { return 0; }" > test1.c

clean:
	rm -f $(wildcard test1*)

# pl13@pl13:~/Documents/git/makefile_tutorial/module_9$ make 
# echo "int main() { return 0; }" > test1.c
# cc    -c -o test1.o test1.c
# cc   test1.o   -o test1