 files_c := $(wildcard *.c)


all: 
	echo $(wildcard ./../*)
all_cfiles:
	echo $(wildcard *.c)
	echo $(files_c)

# pl13@pl13:~/Documents/git/makefile_tutorial/module_7$ make
# echo ./../module_1 ./../module_2 ./../module_3 ./../module_4 ./../module_5 ./../module_6 ./../module_7 ./../module_8 ./../readme.md
# ./../module_1 ./../module_2 ./../module_3 ./../module_4 ./../module_5 ./../module_6 ./../module_7 ./../module_8 ./../readme.md
# pl13@pl13:~/Documents/git/makefile_tutorial/module_7$ make all
# all         all_cfiles  
# pl13@pl13:~/Documents/git/makefile_tutorial/module_7$ make all_cfiles 
# echo file1.c file2.c
# file1.c file2.c
# echo file1.c file2.c
# file1.c file2.c
# pl13@pl13:~/Documents/git/makefile_tutorial/module_7$ 


